### ISSUE TITLE
Unlear licensing situation

### ISSUE THREAD

**Issue by ullenius** [orangelando/nsf#2]
There's no licence included.

The Meapsoft package is [GPL2](https://choosealicense.com/licenses/gpl-2.0) so I guess this makes the whole project GPL 2 by default? You might want to add a licence using [Github's licence picker](https://help.github.com/en/articles/adding-a-license-to-a-repository)

**Comment by orangelando** [comment]
> There's no licence included.
> 
> The Meapsoft package is [GPL2](https://choosealicense.com/licenses/gpl-2.0) so I guess this makes the whole project GPL 2 by default? You might want to add a licence using [Github's licence picker](https://help.github.com/en/articles/adding-a-license-to-a-repository)

Thanks for pointing this out. That package is not necessary to the functioning of this library so I think I'll just pull it.

**Comment by orangelando** [comment]
I added the GPL2 license as the scratch program using Meapsoft's FFT is still pretty useful to me!
